web/go_coup/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

# LOGIN_URL = 'login'
# LOGOUT_URL = 'logout'
# LOGIN_REDIRECT_URL = 'home'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('index.urls', namespace='index')),
    url(r'^user/',include('usermanage.urls', namespace='user')),
    url(r'^store/',include('storemanage.urls', namespace='store')),
    url(r'^customer/',include('customermanage.urls', namespace='customer')),
    url(r'^shopping/',include('market.urls', namespace='market')),
    url(r'^search/', include('haystack.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),

]

web/index/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

app_name = 'index'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detail/(?P<ticket_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^catalog/$', views.catalog, name='catalog'),
    url(r'^search-demo/$', views.searchDemo, name='search-demo'),
    url(r'^get-point/(?P<store>.+)/(?P<key>.+)/$', views.getPoint, name='get-point'),
    url(r'^sw.js', views.sw, name='service-worker'),
    url(r'^brand/(?P<store_id>[0-9]+)/$', views.store, name='store'),
    url(r'^store-list/$', views.store_list, name='store_list'),
]

web/storemanage/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'store'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^currency/add/$', views.currencyRegister, name='currency-register'),
    url(r'^add/$', views.ticketRegister, name='ticket-register'),
    url(r'^create-qr/$', views.createQr, name='create-qr'),
    url(r'^(?P<ticket_id>[0-9]+)/edit/$', views.ticketEdit, name='ticket-edit'),
    url(r'^(?P<ticket_id>[0-9]+)/delete/$', views.ticketDelete, name='ticket-delete'),
    url(r'^(?P<ticket_id>[0-9]+)/dashboard/$', views.ticketDashboard, name='ticket-dashboard'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^get-coupon/(?P<customer>.+)/(?P<key>.+)/$', views.getCoupon, name='get-coupon'),
]

web/usermanage/models/Store.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import JSONField

# Create your models here.

class Store(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    store_name = models.CharField(max_length=30)
    tel = models.CharField(max_length=12, null=True)
    attribute = JSONField(default = dict())
    profile_image_url = models.CharField(max_length=1023, null=True)
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.store_name

web/storemanage/views/createQr.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User
from storemanage.models import Currency
from django.utils.dateparse import parse_date
from django.core.urlresolvers import reverse

from .validateForm import validateQR
from go_coup.host import host_url

import requests

@login_required()
@permission_required('usermanage.store_rights',raise_exception=True)
def createQr(request):
    user = request.user
    currency_list = [{'pk':c.pk,'name':c.name} for c in Currency.objects.filter(store=user)]
    qr = False
    if request.method == 'GET':
        return render(request,'store/create-qr.html', {
            'currency_list': currency_list,
            'qr': qr
        })

    #get data from input
    data = request.POST

    #validate point
    error = validateQR(data)

    if not currency_list:
        error['currency'] = True

    if error:
        return render(request, 'store/create-qr.html', {
        'error': error,
        'currency_list': currency_list
    })


    point = data['point']
    pk_currency = data['currency']
    currency = Currency.objects.get(pk=pk_currency)
    payload = {'price':point, 'currency':pk_currency, 'reuse':'true'}

    #generate redeem code url
    url_gencode = 'http://codegen:8081/save'
    req = requests.post(url_gencode, data=payload)
    key = req.json()['Key']
    
    path_redeem = str(reverse('index:get-point', args=(user, key)))
    url_redeem = host_url + path_redeem

    # show qr code alert
    qr = True

    if qr:
        return render(request,'store/create-qr.html', {
            'point': point,
            'currency': currency,
            'currency_list': currency_list,
            'pk_currency': pk_currency,
            'qr': qr,
            'url_redeem': url_redeem,
        })

web/storemanage/views/dashboard.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User
from storemanage.models import Currency, Ticket
from django.utils.dateparse import parse_date

@login_required()
@permission_required('usermanage.store_rights',raise_exception=True)
def dashboard(request):
    return render(request, 'store/dashboardstore.html', {})

web/storemanage/views/getCoupon.py
from django.shortcuts import render, redirect
from django.contrib.staticfiles.views import serve
from storemanage.models import Ticket, Currency
from customermanage.models import Coupon
from django.contrib.auth.decorators import login_required, permission_required

from django.http import JsonResponse

import requests

@login_required()
@permission_required('usermanage.store_rights',raise_exception=True)
def getCoupon(request, customer, key):
    url_get_pk = 'http://coupon-qr-gen:8082/load'
    payload = {'key':  key}
    req = requests.post(url_get_pk, data=payload)
    found = False
    active = False
    print(req.json())
    if req.json()['Status'] == 'OK':
        found = True
        pk = req.json()['Pk']
        coupon = Coupon.objects.get(id=pk)
        if coupon.active:
            active = True

            coupon.active = False
            coupon.save()
            return render(request, 'store/get-coupon.html', {
                'coupon': coupon,
                'found': found,
                'active': active,
            })
        else:
            return render(request, 'store/get-coupon.html', {
                'coupon': coupon,
                'found': found,
                'active': active,
            })
    else:
        return render(request, 'store/get-coupon.html', {
            'found': found,
        })

web/templates/store/add.html
{% include 'components/store/header.html' %}
<div style="display: flex; justify-content:center;">
    <form method="POST" action=""  style="flex-direction:column; width:60%; margin-top:100px;">
    {% csrf_token %}
        <div class="col-md-6 col-xs-6">
            <label>Name*:</label>
            <input type="text" class="form-control" name="name" value="" required />
        </div>
        <div class="col-md-6 col-xs-6">
            <label>Detail*:</label>
            <input type="text" class="form-control" name="detail" value="" required />
        </div>
        <div class="col-md-6 col-xs-6">
            <label>Price*:</label>
            <input type="number" class="form-control" name="price" value="" required />
        </div>
        <div class="col-md-6 col-xs-6">
            <label>Expire date*:</label>
            <input type="date" class="form-control" name="expire_date" value="" required />
        </div>
        <div class="col-md-6 col-xs-6">
            <br>
            <label class="checkbox">
            Is period?
            <input type="checkbox" value="period" data-toggle="checkbox" class="custom-checkbox" name="is_period">
            <span class="icons">
                <span class="icon-unchecked"></span>
                <span class="icon-checked"></span>
            </span>
            </label>
        </div>
        <div class="col-md-6 col-xs-6">
            <label>Remaining day:</label>
            <input type="number" class="form-control" name="remaining_day" value="" />
        </div>
        <div class="col-md-6 col-xs-6">
            <br>
            <label class="checkbox">
            Is limit?
            <input type="checkbox" value="limit" data-toggle="checkbox" class="custom-checkbox" name="is_limit">
            <span class="icons">
                <span class="icon-unchecked"></span>
                <span class="icon-checked"></span>
            </span>
            </label>
        </div>
        <div class="col-md-6 col-xs-6">
            <label>Remaining:</label>
            <input type="number" class="form-control" name="remain" value="" />
        </div>
        <div class="col-md-6 col-xs-6" style="margin-top:10px;">
            <label>Currency*:</label>
            <select name="currency">
            {% for c in currency_list %}
                <option value="{{c.pk}}">{{c.name}}</option>
            {% endfor %}
            </select>
        </div>
        <div class="col-md-6 col-xs-6">
            <label>Ticket image url*:</label>
            <input type="text" class="form-control" name="ticket_image_url" value="" required />
        </div>
        <div class="col-md-12 col-xs-12">
            <label>Content image url*:</label>
            <input type="text" class="form-control" name="content_image_url" value="" required />
        </div>
        <center>
            <input style="margin:20px; margin-top:30px; width:50%;" class="btn btn-gocoup" type="submit" value="submit" />
        </center>
        {% if error.name_len %}
        <script>
            msg = "Ticket name is too long"
        </script>
        {% endif %}
        {% if error.price_neg %}
        <script>
            msg = "Price must be positive"
        </script>
        {% endif %}
        {% if error.detail_len %}
        <script>
            msg = "Detail is too long"
        </script>
        {% endif %}
        {% if error.remain_neg %}
        <script>
            msg = "Remaining days must be positive"
        </script>
        {% endif %}
        {% if error %}
        <script>
          swal({
            title: msg,
            text: "",
            type: 'error',
          })
        </script>
        {% endif %}
    </form>
</div>
{% include 'components/store/footer.html' %}
    

web/templates/store/addcurrency.html
{% load staticfiles %}
{% include 'components/store/header.html' %}

<form method="POST" action="" style="display:flex; justify-content:center; margin-top:20%;">
    {% csrf_token %}
        <input type="text" name="name" value="US Dollar" style="height: 40px;"/>
        <input style="height:40px; margin-left:10px;" class="btn btn-gocoup" type="submit" value="submit" />
</form>        

{% include 'components/store/footer.html' %}

web/templates/store/create-qr.html
{% load staticfiles %}
{% load qr_code %}
{% include 'components/store/header.html' %}

<div class="container" style="margin-bottom:50px; padding:20% 20% 0 20%;">
        <form method="POST" action="."  style="border:2px solid pink;">
            {% csrf_token %}
            <div class="col-md-8 col-xs-8">
                <label>Point:</label>
                <input type="text" class="form-control" name="point" value="" required />
            </div>
            <br>
            <div class="col-md-4 col-xs-4" style="margin-top:10px;">
                <label>Currency:</label>
                <select name="currency">
                {% for c in currency_list %}
                    <option value="{{c.pk}}">{{c.name}}</option>
                {% endfor %}
                </select>
            </div>
            <center>
                <input style="margin:20px; width:30%;" class="btn btn-gocoup" type="submit" value="submit" />
            </center>
            {% if qr %}
                <script>
                    swal({
                    title: 'Redeem code',
                    type: 'info',
                    html: '<h3>Get {{point}} {{currency}} from QR code</h3>' +
                          '<div>{% qr_from_text url_redeem size="M" %}</div>' +
                          '<h3>or get from this link<h3>' +
                          '<h3>{{url_redeem}}<h3>'
                    })
                </script>
            {% endif %}
            {% if error.digit %}
            <script>
                msg = "Point must be number"
            </script>
            {% endif %}
            {% if error.currency %}
            <script>
                msg = "Don't have any currency"
            </script>
            {% endif %}
            {% if error %}
            <script>
              swal({
                title: msg,
                text: "",
                type: 'error',
              })
            </script>
            {% endif %}
        </form>
</div>

{% include 'components/store/footer.html' %}

web/templates/store/dashboard.html
{% load staticfiles %}
{% include 'components/store/header.html' %}
<div class="row top_tiles" style="display: flex; justify-content: space-between; margin-top: 20px;">
    <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div class="tile-stats">
            <div class="icon"><i class="fa fa-shopping-cart"></i></div>
            <div class="count">30</div>
            <h3>Sold</h3>
            <p>Total sold of this ticket.</p>
        </div>
    </div>
    <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div class="tile-stats">
            <div class="icon"><i class="fa fa-eye"></i></div>
            <div class="count">56</div>
            <h3>Views</h3>
            <p>Total view of this ticket.</p>
        </div>
    </div>
    <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div class="tile-stats">
            <div class="icon"><i class="fa fa-heart"></i></div>
            <div class="count">179</div>
            <h3>Subscribes</h3>
            <p>Total subscribes of this store.</p>
        </div>
    </div>
</div>
<div class="col-md-9 col-sm-12 col-xs-12" style="width:48%; margin-left:4%; margin-top:10px;">
    <p style="text-align:center; margin-top:20px;">Graph show buy and view total</p>
    <canvas id="buyview" style="display:flex"></canvas>
    <script>
    var ctx = document.getElementById('buyview').getContext('2d');
    var chart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: ["1", "2", "3", "4", "5", "6", "7"],
            datasets: [{
                label: "Buy",
                borderColor: 'rgb(153, 255, 204)',
                data: [2, 5, 10, 13, 20, 29, 35],
                fill: false,
                lineTension: 0.00001,
            },
            {
                label: "View",
                borderColor: 'rgb(30, 190, 165)',
                data: [8, 15, 21, 30, 37, 45, 56],
                fill: false,
                lineTension: 0.00001,
            },]
        },
        options: {}
    });
    </script>
</div>
<div class="col-md-9 col-sm-12 col-xs-12" style="width:48%; margin-top:10px;">
    <p style="text-align:center; margin-top:20px;">Graph show percent of this ticket sold</p>
        <canvas id="percentsold" style="display:flex"></canvas>
        <script>
            new Chart(document.getElementById("percentsold"),{
                "type":"doughnut",
                "data":
                    {
                        "labels": ["other ticket","this ticket"],
                        "datasets": 
                            [
                                {
                                    "label":"My First Dataset",
                                    "data": [295, 30],
                                    "backgroundColor": [ "rgb(192, 192, 192)","rgb(153, 255, 153)"]
                                }
                            ]
                    }
                });
        </script>
</div>
<div class="col-md-9 col-sm-12 col-xs-12" style="width:100%; margin-top:20px; padding: 0 10%; 0 10%">
        <p style="text-align:center; margin-top:20px;">Graph show ticket sold per time</p>
            <canvas id="soldtime" style="display:flex"></canvas>
            <script>
                new Chart(document.getElementById("soldtime"),{
                    "type":"bar",
                    "data":
                        {
                            "labels":[
                                "12.00PM - 1.00AM",
                                "1.00AM - 2.00AM",
                                "2.00AM - 3.00AM",
                                "3.00AM - 4.00AM",
                                "4.00AM - 5.00AM",
                                "5.00AM - 6.00AM",
                                "6.00AM - 7.00AM",
                                "7.00AM - 8.00AM",
                                "8.00AM - 9.00AM",
                                "9.00AM - 10.00AM",
                                "10.00AM - 11.00AM",
                                "11.00AM - 12.00AM",
                                "12.00AM - 1.00PM",
                                "1.00PM - 2.00PM",
                                "2.00PM - 3.00PM",
                                "3.00PM - 4.00PM",
                                "4.00PM - 5.00PM",
                                "5.00PM - 6.00PM",
                                "6.00PM - 7.00PM",
                                "7.00PM - 8.00PM",
                                "8.00PM - 9.00PM",
                                "9.00PM - 10.00PM",
                                "10.00PM - 11.00PM",
                                "11.00PM - 12.00PM",
                                ],
                            "datasets":
                                [
                                    {
                                        "label":"Sold",
                                        "data":[0,2,0,0,1,0,3,5,2,7,6,12,6,3,8,10,3,1,2,0,1,0,2,1],
                                        "fill":false,
                                        "backgroundColor":[
                                            "rgba(0, 0, 0, 0.8)",
                                            "rgba(0, 0, 10, 0.8)",
                                            "rgba(0, 0, 20, 0.8)",
                                            "rgba(0, 0, 30, 0.8)",
                                            "rgba(0, 0, 40, 0.8)",
                                            "rgba(0, 0, 50, 0.8)",
                                            "rgba(0, 0, 60, 0.8)",
                                            "rgba(0, 0, 90, 0.8)",
                                            "rgba(0, 0, 120, 0.8)",
                                            "rgba(0, 0, 150, 0.8)",
                                            "rgba(0, 0, 180, 0.8)",
                                            "rgba(0, 0, 210, 0.8)",
                                            "rgba(0, 0, 255, 0.8)",
                                            "rgba(0, 0, 210, 0.8)",
                                            "rgba(0, 0, 180, 0.8)",
                                            "rgba(0, 0, 150, 0.8)",
                                            "rgba(0, 0, 120, 0.8)",
                                            "rgba(0, 0, 90, 0.8)",
                                            "rgba(0, 0, 60, 0.8)",
                                            "rgba(0, 0, 50, 0.8)",
                                            "rgba(0, 0, 40, 0.8)",
                                            "rgba(0, 0, 30, 0.8)",
                                            "rgba(0, 0, 20, 0.8)",
                                            "rgba(0, 0, 10, 0.8)",
                                            ],
                                    }
                                ]
                        },
                    "options":
                        {"scales":{"yAxes":[{"ticks":{"beginAtZero":true}}]}}});
            </script>
    </div>
{% include 'components/store/footer.html' %}

web/templates/store/dashboardstore.html
{% load staticfiles %}
{% include 'components/store/header.html' %}
<div class="row tile_count" style="margin-left:10px;">
        <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
          <span class="count_top"><i class="fa fa-user"></i> Total Users</span>
          <div class="count">1081</div>
          <span class="count_bottom"><i class="green">9% </i> From last Week</span>
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
          <span class="count_top"><i class="fa fa-shopping-cart"></i> Total Buys</span>
          <div class="count">325</div>
          <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>3% </i> From last Week</span>
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
          <span class="count_top"><i class="fa fa-shopping-cart"></i> Average Buys per day</span>
          <div class="count green">27.08</div>
          <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>6% </i> From last Week</span>
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
          <span class="count_top"><i class="fa fa-eye"></i> Total Views</span>
          <div class="count">500</div>
          <span class="count_bottom"><i class="red"><i class="fa fa-sort-desc"></i>5% </i> From last Week</span>
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
          <span class="count_top"><i class="fa fa-eye"></i> Average Views per day</span>
          <div class="count">41.67</div>
          <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>1% </i> From last Week</span>
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
          <span class="count_top"><i class="fa fa-heart"></i> Total Subscribes</span>
          <div class="count">179</div>
          <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>2% </i> From last Week</span>
        </div>
      </div>
<div class="col-md-9 col-sm-12 col-xs-12" style="width:100%; padding: 0 20%; 0 20%; margin-top:10px;">
            <p style="text-align:center; margin-top:20px;">Graph show view and buy per day</p>
            <canvas id="buyviewperday" style="display:flex"></canvas>
            <script>
            var ctx = document.getElementById('buyviewperday').getContext('2d');
            var chart = new Chart(ctx, {
                type: 'line',
                data: {
                    labels: ["9 Nov", "10 Nov", "11 Nov", "12 Nov", "13 Nov", "14 Nov", "15 Nov", "16 Nov", "17 Nov", "18 Nov", "19 Nov", "20 Nov"],
                    datasets: [
                    {
                        label: "View",
                        borderColor: 'rgb(139,0,139)',
                        data: [28, 38, 41, 39, 43, 38, 32, 45, 35, 27, 39, 27],
                        fill: false,
                        lineTension: 0.00001,
                        fill: true,
                    },
                    {
                        label: "Buy",
                        borderColor: 'rgb(30,144,255)',
                        data: [20, 31, 21, 25, 33, 19, 21, 27, 22, 25, 32, 25],
                        fill: false,
                        lineTension: 0.00001,
                        fill: true,
                    },
                    ]
                },
                options: {}
            });
            </script>
        </div>
<div class="col-md-9 col-sm-12 col-xs-12" style="width:100%; margin-top:20px; padding: 0 20%; 0 20%">
        <p style="text-align:center; margin-top:20px;">Graph show view and buy of each tickets</p>
            <canvas id="soldtime" style="display:flex"></canvas>
            <script>
                new Chart(document.getElementById("soldtime"),{
                    "type":"bar",
                    "data":
                        {
                            "labels":[
                                "Discount 50 Baht",
                                "Free drink",
                                "Buy 1 get 1",
                                "Discount 20%"
                                ],
                            "datasets":
                                [
                                    {
                                        "label":"View",
                                        "data":[8, 10, 17, 6],
                                        "fill":false,
                                        "backgroundColor":"rgba(255, 215, 53, 0.5)",
                                        "borderColor":"rgba(255, 215, 53)",
                                        "borderWidth":2,
                                    },
                                    {
                                        "label":"Buy",
                                        "data":[5, 6, 12, 3],
                                        "fill":false,
                                        "backgroundColor":"rgba(0, 153, 0, 0.5)",
                                        "borderColor":"rgba(0, 153, 0)",
                                        "borderWidth":2,
                                    },
                                ]
                            
                        },
                    "options":
                        {"scales":{"yAxes":[{"ticks":{"beginAtZero":true}}]}}});
            </script>
    </div>
    <div class="col-md-9 col-sm-12 col-xs-12" style="width:100%; margin-top:10px; margin-bottom:20px; padding: 0 20%; 0 20%;">
            <p style="text-align:center; margin-top:20px;">Graph show view and buy total</p>
            <canvas id="buyview" style="display:flex"></canvas>
            <script>
            var ctx = document.getElementById('buyview').getContext('2d');
            var chart = new Chart(ctx, {
                type: 'line',
                data: {
                    labels: ["9 Nov", "10 Nov", "11 Nov", "12 Nov", "13 Nov", "14 Nov", "15 Nov", "16 Nov", "17 Nov", "18 Nov", "19 Nov", "20 Nov"],
                    datasets: [
                    {
                        label: "View",
                        borderColor: 'rgb(64,224,208)',
                        data: [8, 15, 21, 30, 37, 45, 56, 63, 72, 89, 91, 100],
                        fill: false,
                        lineTension: 0.00001,
                    },
                    {
                        label: "Buy",
                        borderColor: 'rgb(240,128,128)',
                        data: [2, 5, 10, 13, 20, 29, 35, 42, 56, 61, 67, 72],
                        fill: false,
                        lineTension: 0.00001,
                    },
                    ]
                },
                options: {}
            });
            </script>
        </div>
{% include 'components/store/footer.html' %}

web/templates/store/index.html
{% load staticfiles %}
{% include 'components/store/header.html' %}
<div class="row top_tiles" style="display: flex; justify-content: space-between; margin-top: 20px;">
  <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
    <div class="tile-stats">
      <div class="icon"><i class="fa fa-shopping-cart"></i></div>
      <div class="count">325</div>
      <h3>Sold</h3>
      <p>Total sold of all tickets.</p>
    </div>
  </div>
  <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
    <div class="tile-stats">
      <div class="icon"><i class="fa fa-eye"></i></div>
      <div class="count">500</div>
      <h3>Views</h3>
      <p>Total view of all tickets.</p>
    </div>
  </div>
  <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
    <div class="tile-stats">
      <div class="icon"><i class="fa fa-heart"></i></div>
      <div id="sub-num" class="count">{{ subscribes_len }}</div>
      <h3>Subscribes</h3>
      <p>Total subscribes of this store.</p>
    </div>
  </div>
</div>
<div style="display:flex; justify-content: space-around; padding: 20px;">
<table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Detail</th>
        <th>Date</th>
        <th>Dashboard</th>
        <th>Promote</th>        
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for ticket in tickets %}
        <tr>
          <td>{{ ticket.name }}</td>
          <td>{{ ticket.price }} {{ ticket.currency }}</td>
          <td>{{ ticket.detail }}</td>
          <td>{{ ticket.expire_date }}</td>
          <td><a href="{% url 'store:ticket-dashboard' ticket.id %}"><i class="fa fa-line-chart"></i></a></td>
          <td> 
            <a onclick="promote('{{ ticket.name }}', '{{ ticket.detail }}', '{{ ticket.content_image_url }}')"><i class="fa fa-bullhorn" aria-hidden="true"></i></a>
          </td>
          <td><a href="{% url 'store:ticket-edit' ticket.id %}"><i class="fa fa-pencil"></i></a></td>
          <td>
            <a onclick="deleteTicket('{% url 'store:ticket-delete' ticket.id %}')"><i class="fa fa-trash"></i></a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <div id="userId" value="{{ user.id }}"></div>
  <div id="storeName" value="{{ user.store }}"></div>
</div>

<script>
  var userId = $('#userId').attr('value')
  var storeName = $('#storeName').attr('value')
  var host = 'localhost'
 
  function promote(name, detail, content_image_url) {
    $.ajax({
      type: 'POST',
      url: 'http://' + host + ':8080/notify/store/' + userId,
      data: {
        'title':  'New Coupon from  ' + storeName,
        'message': 'name: ' + name + '  \n detail: ' + detail,
        'image': content_image_url,
      },
      success: function() {

      },
      dataType: 'json'
    })
  }

  function deleteTicket(ticketUrl) {
    swal({
      title: 'Are you sure?',
      text: "You won't be able to revert this!",
      type: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Yes, delete it!'
    }).then(function () {
      swal(
        'Deleted!',
        'Your row has been deleted.',
        'success',
      )
    }).then(function () {
      window.location.assign(ticketUrl);
    })
  }
</script>
{% if error %}
<script>
  swal(
    'Error !',
    '{{ error }}',
    'error'
  )
  window.history.replaceState(null ,null, '/store')
</script>
{% endif %}
{% include 'components/store/footer.html' %}