web/go_coup/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

# LOGIN_URL = 'login'
# LOGOUT_URL = 'logout'
# LOGIN_REDIRECT_URL = 'home'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('index.urls', namespace='index')),
    url(r'^user/',include('usermanage.urls', namespace='user')),
    url(r'^store/',include('storemanage.urls', namespace='store')),
    url(r'^customer/',include('customermanage.urls', namespace='customer')),
    url(r'^shopping/',include('market.urls', namespace='market')),
    url(r'^search/', include('haystack.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),

]

web/index/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

app_name = 'index'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detail/(?P<ticket_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^catalog/$', views.catalog, name='catalog'),
    url(r'^search-demo/$', views.searchDemo, name='search-demo'),
    url(r'^get-point/(?P<store>.+)/(?P<key>.+)/$', views.getPoint, name='get-point'),
    url(r'^sw.js', views.sw, name='service-worker'),
    url(r'^brand/(?P<store_id>[0-9]+)/$', views.store, name='store'),
    url(r'^store-list/$', views.store_list, name='store_list'),
]

web/storemanage/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'store'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^currency/add/$', views.currencyRegister, name='currency-register'),
    url(r'^add/$', views.ticketRegister, name='ticket-register'),
    url(r'^create-qr/$', views.createQr, name='create-qr'),
    url(r'^(?P<ticket_id>[0-9]+)/edit/$', views.ticketEdit, name='ticket-edit'),
    url(r'^(?P<ticket_id>[0-9]+)/delete/$', views.ticketDelete, name='ticket-delete'),
    url(r'^(?P<ticket_id>[0-9]+)/dashboard/$', views.ticketDashboard, name='ticket-dashboard'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^get-coupon/(?P<customer>.+)/(?P<key>.+)/$', views.getCoupon, name='get-coupon'),
]

web/usermanage/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'user'
LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = 'home'
SOCIAL_AUTH_FACEBOOK_KEY = '504951239878757'  # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = 'd6e8030eb8a53f82a34c169139993bd4' # App Secret

urlpatterns = [
    url(r'^register/$', views.customerRegister, name='customer-register'),
    url(r'^store-register/$', views.storeRegister, name='store-register'),
    url(r'^login/$',views.singin, name='login'),
    url(r'^logout/$',views.signout, name='logout'),
    url(r'^tempprofile/$',views.profile, name='profile'),
    url(r'^profile/$',views.customerProfile, name='customer-profile'),
    url(r'^coupon/$',views.customerCoupon, name='customer-coupon'),
    url(r'^wallet/$',views.customerWallet, name='customer-wallet'),
    url(r'^customertest/$',views.customertest, name='customertest'),
    url(r'^storetest/$',views.storetest, name='storetest'),
    url(r'^setting/$',views.customerSetting, name='customer-setting'),
]

web/usermanage/models/Store.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import JSONField

# Create your models here.

class Store(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    store_name = models.CharField(max_length=30)
    tel = models.CharField(max_length=12, null=True)
    attribute = JSONField(default = dict())
    profile_image_url = models.CharField(max_length=1023, null=True)
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.store_name

web/templates/components/store/footer.html
{% load staticfiles %}
<div class="footer">
    <div class="col-sm-4 col-xs-12" style="position:fixed; bottom:10px; margin:10px; left:0px;">
      <h4>Contact us</h4>
      <h5>Dev: <a class="footer-link" href="https://twitter.com/monthol8th">@monthol8th</a></h5>
      <h5>CEO: <a class="footer-link" href="https://www.facebook.com/evee.monpriya">evee.monpriya</a></h5>
    </div>
  </div>
  </div>
</body>
</html>

web/templates/components/store/header.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'css/flat-ui.min.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/detail.css' %}">
  <link rel="stylesheet" href="{% static 'css/profile.css' %}">
  <link rel="stylesheet" href="{% static 'css/cart.css' %}">
  <link rel="stylesheet" href="{% static 'css/coupon.css' %}">
  <link rel="stylesheet" href="{% static 'css/login.css' %}">
  <link rel="stylesheet" href="{% static 'css/store.css' %}">
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

  <title>Store Management</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.bundle.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.9.1/sweetalert2.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.9.1/sweetalert2.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
  <link href="https://fonts.googleapis.com/css?family=Kanit:300,400,700" rel="stylesheet">
  <script src="{% static 'js/script.js' %}"></script>
  <script src="{% static 'js/flat-ui.min.js' %}"></script>
  <script src="https://use.fontawesome.com/de2946df28.js"></script>
</head>
<body>
    <div class="container body">
        <!-- <div class="main_container"> -->
          <div class="col-sm-2 left_col" style="width:250px; height:100vh; bottom:0; position:fixed">
            <div class="left_col scroll-view">
              <div class="navbar" style="border: 0;">
                <a href="/store" class="site_title"><i class="fa fa-shopping-cart"></i> <span>Store manage</span></a>
              </div>
  
              <div class="clearfix"></div>
  
              <!-- menu profile quick info -->
              <div class="profile clearfix">
                <div class="profile_info">
                  <span>Welcome,</span>
                  <h2>{{ user.username }}</h2>
                </div>
              </div>
              <!-- /menu profile quick info -->
  
              <br />
  
              <!-- sidebar menu -->
              <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                <div class="menu_section">
                  <h3>General</h3>
                  <ul class="nav side-menu">
                  {% if request.path == '/store/' %}
                    <li style="background-color:rgb(255, 113, 139);"><a href="/store"><i class="fa fa-home"></i> Home </a></li>
                  {% else %}
                    <li><a href="/store"><i class="fa fa-home"></i> Home </a></li>
                  {% endif %}
                    <li class="disabled"><a><i class="fa fa-edit"></i> Edit profile</a></li>
                  {% if request.path == '/store/currency/add/' %}
                    <li style="background-color:rgb(255, 113, 139);"><a href="{% url 'store:currency-register' %}"><i class="fa fa-money"></i> Add currecy</a></li>
                  {% else %}
                    <li><a href="{% url 'store:currency-register' %}"><i class="fa fa-money"></i> Add currecy</a></li>
                  {% endif %}
                  {% if request.path == '/store/add/' %}
                    <li style="background-color:rgb(255, 113, 139);"><a href="{% url 'store:ticket-register' %}"><i class="fa fa-ticket"></i> Add ticket</a></li>
                  {% else %}
                    <li><a href="{% url 'store:ticket-register' %}"><i class="fa fa-ticket"></i> Add ticket</a></li>
                  {% endif %}
                  {% if '/edit/' in request.path %}
                    <li class="disabled" style="background-color:rgb(255, 113, 139);"><a><i class="fa fa-pencil-square-o"></i> Edit ticket</a></li>
                  {% else %}
                    <li class="disabled"><a><i class="fa fa-pencil-square-o"></i> Edit ticket</a></li>
                  {% endif %}
                  {% if '/dashboard/' in request.path %}
                    <li class="disabled" style="background-color:rgb(255, 113, 139);"><a><i class="fa fa-bar-chart"></i> Dashboard</a></li>
                  {% else %}
                    <li><a href="{% url 'store:dashboard' %}"><i class="fa fa-bar-chart"></i> Dashboard</a></li>
                  {% endif %}
                  {% if '/store/create-qr/' in request.path %}
                    <li style="background-color:rgb(255, 113, 139);"><a href="{% url 'store:create-qr' %}"><i class="fa fa-qrcode"></i> Create QR</a></li>
                  {% else %}
                    <li><a href="{% url 'store:create-qr' %}"><i class="fa fa-qrcode"></i> Create QR</a></li>
                  {% endif %}
                  </ul>
                </div>
  
              </div>
              <!-- /sidebar menu -->
            </div>
          </div>
        <!-- </div> -->
        <div class="main_container" style="margin-left:250px;">
          <!-- top navigation -->
          <div class="top_nav">
            <div class="nav_menu" style="display:flex; justify-content: space-between;">
              <nav></nav>
              <nav>
                <div class="nav-btn-logo">
                  <a href="/">
                    <img class="logo" src="{% static 'images/logo-pink.png' %}" alt="logo">
                  </a>
                </div>
              </nav>
              <nav>
                <div class="right">
                  {% if user.is_authenticated %}
                  <div class="nav-btn" style="background-color:#d4286a">
                    <a href="{% url 'user:logout' %}">
                      Logout
                    </a>
                  </div>
                  {% else %}
                    <a href="/user/login">
                      <div class="nav-btn">
                        Login
                      </div>
                    </a>
                    <a href="/user/register">
                      <div class="nav-btn">
                        Register
                      </div>
                    </a>
                  {% endif %}
                </div>
              </nav>
            </div>
          </div>
          <!-- /top navigation -->
      
<script>
  $()
</script>