web/customermanage/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'customer'
urlpatterns = [
    url(r'^motherload/$', views.motherload,name='motherload')
]

web/go_coup/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

# LOGIN_URL = 'login'
# LOGOUT_URL = 'logout'
# LOGIN_REDIRECT_URL = 'home'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('index.urls', namespace='index')),
    url(r'^user/',include('usermanage.urls', namespace='user')),
    url(r'^store/',include('storemanage.urls', namespace='store')),
    url(r'^customer/',include('customermanage.urls', namespace='customer')),
    url(r'^shopping/',include('market.urls', namespace='market')),
    url(r'^search/', include('haystack.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),

]

web/index/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

app_name = 'index'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detail/(?P<ticket_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^catalog/$', views.catalog, name='catalog'),
    url(r'^search-demo/$', views.searchDemo, name='search-demo'),
    url(r'^get-point/(?P<store>.+)/(?P<key>.+)/$', views.getPoint, name='get-point'),
    url(r'^sw.js', views.sw, name='service-worker'),
    url(r'^brand/(?P<store_id>[0-9]+)/$', views.store, name='store'),
    url(r'^store-list/$', views.store_list, name='store_list'),
]

web/market/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'market'
urlpatterns = [
    url(r'^purchase/$', views.purchase,name='purchase'),
    url(r'^checkout/$', views.checkout,name='checkout')
]

web/customermanage/models/Coupon.py
from django.db import models
from storemanage.models.Currency import Currency
from storemanage.models.Ticket import Ticket
from django.contrib.auth.models import User
from django.contrib.postgres.fields import JSONField
# Create your models here.

class Coupon(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    remaining_date = models.DateTimeField(null=True)
    active = models.BooleanField(default=True)
    attribute = JSONField(default = dict())

web/customermanage/models/Wallet.py
from django.db import models
from storemanage.models.Currency import Currency
from storemanage.models.Ticket import Ticket
from django.contrib.auth.models import User
from django.contrib.postgres.fields import JSONField
# Create your models here.
class Wallet(models.Model):
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.PositiveIntegerField(default=0)
    attribute = JSONField(default = dict())

web/storemanage/models/Ticket.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import JSONField
from .Currency import Currency

# Create your models here.

class Ticket(models.Model):
    name = models.CharField(max_length=127)
    price = models.PositiveIntegerField()
    detail = models.TextField(max_length=1023)
    expire_date = models.DateField() #วันหมดอายุของคูปอง
    is_period = models.BooleanField()
    remaining_day = models.PositiveIntegerField(null=True) #จำนวนวันที่คูปองสามารถใช้งานได้ นับตั้งแต่การซื้อ
    is_limit = models.BooleanField()
    remain = models.IntegerField(null=True)  #จำนวนที่ยังเหลืออยู่
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE)
    store = models.ForeignKey(User, on_delete=models.CASCADE)
    ticket_image_url = models.CharField(max_length=1023, null=True)
    content_image_url = models.CharField(max_length=1023, null=True)
    attribute = JSONField(default=dict())
    available = models.BooleanField(default=True)
    stat = JSONField(default=dict())
    raw_stat = JSONField(default=dict())

web/usermanage/models/Store.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import JSONField

# Create your models here.

class Store(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    store_name = models.CharField(max_length=30)
    tel = models.CharField(max_length=12, null=True)
    attribute = JSONField(default = dict())
    profile_image_url = models.CharField(max_length=1023, null=True)
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.store_name

web/usermanage/views/profile.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from django.contrib.auth.forms import UserCreationForm
from customermanage.models import Coupon, Wallet
from storemanage.models import Ticket
# Create your views here.
from usermanage import models

@login_required()
def profile(request):
    user = request.user
    data = {'username':user.username,'email':user.email, 'firstname':user.first_name, 'lastname':user.last_name}
    if user.groups.filter(name='store').exists():
        store = models.Store.objects.get(user=user)
        data['store_name']=store.store_name
    elif user.groups.filter(name='customer').exists():
        customer = models.Customer.objects.get(user=user)
        data['first_name']=customer.first_name
        data['last_name']=customer.last_name
    return render(request,'usermanage/profile.html', context={'d':data})

web/templates/index/brand-list.html
{% load staticfiles %}
{% include 'components/header.html' %}
<div class="full-container">
    <div class="content row">
        {% for store in stores %}
            {% if forloop.counter < 10 %}
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <a class="coup-link" href="{% url 'index:store' store.id %}">
                        <div class="brand-sell">

                            <img
                                class="coup-img"
                                src="{{ store.profile_image_url }}"
                                onError="this.onerror=null;this.src='https://kfcbd.com/wp-content/uploads/2016/11/kfc-logo.png'"
                            >
                            <div class="coup-text-wrapper">
                            <div class="coup-left">
                                <p class="coup-text">name: {{ store.store_name }}</p>
                            </div>
                            </div>
                        </div>
                    </a>
                </div>
            {% endif %}
            {% if forloop.counter|divisibleby:"3" %}
                </div><div class="row">
            {% endif %}
        {% endfor %}
      </div>
        <div class="row">
          <div class="col-xs-12 text-right" style="margin-top:20px;">
            <a href="{% url 'index:catalog' %}">
              <button class="btn btn-gocoup">Show more</button>
            </a>
          </div>
        </div>
    </div>
</div>

web/templates/index/cart.html
{% include 'components/header.html' %}

<div class="full-container">
  <div class="cart-wrapper container">
    {% for ticket in tickets %}
      <div class="row" id="row_{{ ticket.id }}">
        <div class="col-sm-6 col-sm-offset-3 col-xs-12">
          <div class="list">
            <img
              onError="this.onerror=null;this.src='https://assets.kfc.co.uk/3f040df6-0c9cdd0f/wicked-variety-bucket-320w.jpeg'"
              class="list-image" src="{{ ticket.content_image_url }}"
              alt="detail content"
            >
            <div class="list-content">
              <div style="display: flex; justify-content: space-between;">
                <p>name: {{ ticket.name }}</p>
                <a class="btn" onclick="deleteTicketFromCart({{  ticket.id }})">
                  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                </a>
              </div>
              <p id='ticket_{{ ticket.id }}'>quantity: 0</p>
              <button class='add-btn btn btn-default' onclick="incrementTicket({{ ticket.id }})">+</button>
              <button class='add-btn btn btn-default' onclick="handlerDelete({{ ticket.id }})">-</button>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
    <div class="row cart-btn-wrapper">
      <div class="col-xs-12">
        <button class="btn btn-gocoup">shop</button>
        <form class="buy-btn-form" method="POST" action="{% url 'market:checkout' %}">
            {% csrf_token %}
            <button id="buy-btn" class="btn btn-gocoup" type="submit" name="cart" value="">Buy</button>
        </form>
      </div>
    </div>
  </div>
</div>
<script>
  $('#buy-btn').val(JSON.stringify(cartItemToObject()))
  var tickets = cartItemToObject()
  tickets.forEach(function(t) {
    var numElement = document.getElementById('ticket_' + t.id);
    numElement.innerText = 'quantity: ' + t.count;
  });
</script>

{% include 'components/footer.html' %}

web/templates/index/catalog.html
{% load staticfiles %}
{% include 'components/header.html' %}
<!--
<img
    src="https://f.ptcdn.info/808/052/000/ou0idx1t5MrjxrpCEIA-o.jpg" \
    width="100%"
    border="0" /> -->
<div class="full-container">
    <div class="container">
    <div class="row search-wrapper">
      <div class="col-sm-8 col-sm-offset-2 col-xs-12">
        <div class="search-box">
            <form action="/search" method="GET" class="search-form">
                {% csrf_token %}
                <input id="id_q" type="text" name="q" maxlength="127" class="form-control search-input" placeholder="find coupon here.."/>
                <button class="btn btn-link search-btn">
                    <i class="glyphicon glyphicon-search"></i>
                </button>
            </form>
        </div>
      </div>
    </div>
    
    <div class="content row">
        {% for ticket in tickets %}
            <div class="col-md-4 col-sm-6 col-xs-12">
                <a class="coup-link" href="{% url 'index:detail' ticket.id %}">
                    <div class="coupon-sell">

                        <img
                            class="coup-img"
                            src="{{ ticket.ticket_image_url }}"
                            onError="this.onerror=null;this.src='https://kfcbd.com/wp-content/uploads/2016/11/kfc-logo.png'"
                        >
                        <div class="coup-text-wrapper">
                        <div class="coup-left">
                            <p class="coup-text">name: {{ ticket.name }}</p>
                            <p class="coup-text">exp: {{ ticket.expire_date }}</p>
                        </div>
                        <div class="coup-right">
                            <p class="coup-text">{{ ticket.price }} {{ ticket.currency }}</p>
                        </div>
                        </div>
                    </div>
                </a>
            </div>
            {% if forloop.counter|divisibleby:"3" %}
                </div><div class="content row">
            {% endif %}
        {% endfor %}
    </div>
    </div>
</div>

{% include 'components/footer.html' %}

web/templates/index/coupon.html
{% include 'components/header.html' %}
{% load qr_code %}
<div class="full-container">
  <div class="container">
    {% include 'components/tabbar.html' %}

    <h1 class="pink">Current used</h1>
    <div class="container">
    {% for c in coupon %}
      <div class="row">
        <div class="coupon">
          <div class="coupon-img">
            <img class="img-coupon" src="{{c.image_url}}" alt="">
          </div>
          <div class="coupon-content">
            <p>Name: {{c.name}}</p>
            <p>Exp: {{c.exp}}</p>
            <p>Description: {{c.detail}}</p>
            <!-- <p>coupon_url: {{ coupon_url.forloop_counter }}</p> -->
          </div>
          <!-- <button data-toggle="modal" data-target="#exampleModal"> -->
          <a data-toggle="modal" data-target="#exampleModal" class="show-modal">
            <div id="qr_{{ forloop.counter }}"></div>
              <!-- {% qr_from_text c.forloop.coun size="M" %} -->
          <!-- </button> -->
          </a>
        </div>
      </div>
     {% endfor %}
    </div>
  </div>
</div>
{% for c in coupon_url %}
  <script>
    new QRCode(document.getElementById("qr_{{ forloop.counter }}"), {
      text: "{{ c }}",
      width: 128,
      height: 128,
    });
    $('#qr_{{ forloop.counter }}').parent().attr('url', '{{ c }}')
  </script>
{% endfor %}
<script>
    $('a.show-modal').click(function() {
      var url = $('a.show-modal')[0].attributes[3].value;
      var qrcode = document.getElementById("qrcode-modal");
      if(qrcode.childNodes.length === 0) {
        new QRCode(document.getElementById("qrcode-modal"), {
          text: url,
          width: 256,
          height: 256,
        });
      }
      $('#modal-text').text($(this).attr('url'));
    });

</script>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="exampleModalLabel">Scan QR Code</h3>
        <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button> -->
      </div>
      <div class="modal-body text-center">
        <div id="qrcode-modal"></div>
        <div id="modal-text"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>

{% include 'components/footer.html' %}

web/templates/index/detail.html
{% load staticfiles %}
{% include 'components/header.html' %}
<div class="full-container">
  <div class="container">
    <div class="content row">
      <div class="col-md-6 col-xs-12">
        <div class="detail-discription">
          <div class="detail-head" style="display:flex;">
            <a class="coup-link" href="{% url 'index:store' store.pk %}">
              <img class="profile-image" src="{{ store.profile_image_url}}" style="margin-top:5px;" alt="head">
            </a>
            <div class="detail-head-title">
              <a class="detail-head" href="{% url 'index:store' store.id %}">
                <h1 style="margin-left:10px;">{{ ticket.store }}</h1>
              </a>
              <p style="margin-left:10px;">exp: {{ ticket.expire_date }}</p>
              {% if not is_store and user.is_authenticated %}
                <div><button id="subscribe-btn" class="btn"></i></button></div>  
              {% endif %}
            </div>
          </div>
          <hr>
          <img
            class="detail-content-image"
            src="{{ ticket.content_image_url }}"
            alt="detail content"
            onError="this.onerror=null;this.src='https://assets.kfc.co.uk/3f040df6-0c9cdd0f/wicked-variety-bucket-320w.jpeg'"
          >
        </div>
      </div>
      <div class="col-md-6 col-xs-12">
        <div class="detail">
          <div class="detail-discription">  
            <img class="detail-head-image" src="{{ ticket.ticket_image_url }}" style="margin-top:10px; margin-bottom:10px">
              <table class="detail-table">
                <tr class="detail-tr">
                  <td class="align-left">Name:</td>
                  <td class="align-right">{{ ticket.name }}</td>
                </tr>
                <tr class="detail-tr">
                  <td class="align-left">Price:</td>
                  <td class="align-right">{{ ticket.price }} {{ ticket.currency }}</td>
                </tr>
                {% if ticket.is_limit %}
                  <tr class="detail-tr">
                    <td class="align-left">Amount:</td>
                    <td class="align-right">{{ ticket.remain }}</td>
                  </tr>
                {% endif %}
                {% if ticket.is_period %}
                  <tr class="detail-tr">
                    <td class="align-left" colspan="2">Coupon will expire after {{ ticket.remaining_day }} days</td>
                  </tr>
                {% endif %}
              </table>
          </div>
          <div class="detail-discription">
            <p>{{ ticket.detail }}</p>
          </div> 
          {% if not is_store and user.is_authenticated %}
            <form class="buy-btn-form" method="POST" action="{% url 'market:purchase' %}">
                {% csrf_token %}
                <button class="btn buy-btn" type="submit" name="ticket_id" value="{{ticket.pk}}">Buy</button>
            </form>
            <button class="btn buy-btn" onclick="handlerAddToCart({{ ticket.id }}, '{{ ticket.name }}')">add to cart</button>
          {% endif %}
        </div>
      </div>
    </div>
    <div id="userId" value="{{ user.id }}"></div>
    <div id="storeId" value="{{ ticket.store.id }}"></div>    
  </div>
{% if success %}
  <script>
    swal({
      title: 'Success!',
      text: "add {{ ticket.name }} to your wallet.",
      type: 'success',
    })
  </script>
{% endif %}
{% if fail %}
<script>
  swal({
    title: 'Fail!',
    text: "not enough currency",
    type: 'error',
  })
</script>
{% endif %}
{% include 'components/footer.html' %}

web/templates/index/get-point.html
{% load staticfiles %}
{% load qr_code %}
{% include 'components/header.html' %}

<div class="container" style="margin-bottom:50px;">
    
    {% if user.is_authenticated %}
        {% if not is_store %}
            {% if can_redeem %}
                {% if not already_redeem %}
                    <script>
                        swal({
                        title: 'Success',
                        type: 'success',
                        html: '<h3>Get {{price}} {{currency}}</h3>'
                        })
                    </script>
                {% else %}
                    <script>
                        swal({
                        title: 'Error',
                        type: 'error',
                        html: '<h3>Already redeem</h3>'
                        })
                    </script>
                {% endif %}
            {% else %}
                <script>
                    swal({
                    title: 'Error',
                    type: 'error',
                    html: '<h3>Not found key</h3>'
                    })
                </script>
            {% endif %}
        {% else %}
            <script>
                swal({
                title: 'Error',
                type: 'error',
                html: '<h3>For user only</h3>'
                })
            </script>
        {% endif %}
    {% else %}
        <script>
            swal({
            title: 'Error',
            type: 'error',
            html: '<h3>Please login for redeem point</h3>'
            })
        </script>
    {% endif %}
</div>

{% include 'components/store/footer.html' %}

web/templates/index/index.html
{% load staticfiles %}
{% include 'components/header.html' %}
<!--
<img
    src="https://f.ptcdn.info/808/052/000/ou0idx1t5MrjxrpCEIA-o.jpg" \
    width="100%"
    border="0" /> -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
        <img src="{% static 'images/cover1.png' %}" alt="cover" style="width:100%;">
        </div>

        <div class="item">
        <img src="{% static 'images/cover2.png' %}" alt="cover" style="width:100%;">
        </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
    </a>

    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
    </a>

</div>
<div class="full-container">
    <div class="container">

    <div class="row search-wrapper">
      <div class="col-sm-8 col-sm-offset-2 col-xs-12">
        <div class="search-box">
          <form action="/search" method="GET" class="search-form">
            {% csrf_token %}
            <input id="id_q" type="text" name="q" maxlength="127" class="form-control search-input" placeholder="find coupon here.."/>
            <button class="btn btn-link search-btn">
                <i class="glyphicon glyphicon-search"></i>
            </button>
          </form>
        </div>
      </div>
    </div>

    <!-- โชว์ตั๋ว -->
    <div class="content row">
        {% for ticket in tickets %}
            {% if forloop.counter < 10 %}
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <a class="coup-link" href="{% url 'index:detail' ticket.id %}">
                        <div class="coupon-sell">

                            <img
                                class="coup-img"
                                src="{{ ticket.ticket_image_url }}"
                                onError="this.onerror=null;this.src='https://kfcbd.com/wp-content/uploads/2016/11/kfc-logo.png'"
                            >
                            <div class="coup-text-wrapper">
                                <!-- <div class="coup-mini-logo">
                                        <img
                                            class="profile-mini-logo"
                                            src="{{ ticket.store.profile_image_url }}"
                                            onError="this.onerror=null;this.src='https://kfcbd.com/wp-content/uploads/2016/11/kfc-logo.png'"
                                        >
                                </div> -->
                                <div class="coup-left">
                                    <p class="coup-text">name: {{ ticket.name }}</p>
                                    <p class="coup-text">exp: {{ ticket.expire_date }}</p>
                                </div>
                                <div class="coup-right">
                                    <p class="coup-text">{{ ticket.price }} {{ ticket.currency }}</p>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            {% endif %}
            {% if forloop.counter|divisibleby:"3" %}
                </div><div class="row">
            {% endif %}
        {% endfor %}
      </div>
        <div class="row">
          <div class="col-xs-12 text-right" style="margin-top:20px;">
            <a href="{% url 'index:store_list' %}" class="link-btn">
              <button class="btn btn-gocoup">
                Show Store
              </button>
            </a>
            <a href="{% url 'index:catalog' %}">
              <button class="btn btn-gocoup">Show more</button>
            </a>
        </div>
    </div>
</div>
{% if success %}
<script>
  swal({
    title: 'Success!',
    text: "add {{ ticket.name }} to your wallet.",
    type: 'success',
  })
  localStorage.removeItem('gocoup-cart');
</script>
{% endif %}
{% if fail %}
<script>
swal({
  title: 'Fail!',
  text: "not enough currency",
  type: 'error',
})
</script>
{% endif %}

{% include 'components/footer.html' %}

web/templates/index/profile.html
{% include 'components/header.html' %}

<div class="full-container">

  <div class="container">
    {% include 'components/tabbar.html' %}
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <h3>
            <span class="hilight">Name:</span> {% if 'first_name' in data %}{{ data.first_name }}{% endif %}
          </h3>
          <h3>
            <span class="hilight">Last Name:</span> {% if 'last_name' in data %}{{ data.last_name }}{% endif %}
          </h3>
          <h3>
            <span class="hilight">Email:</span> {% if 'email' in data %}{{ data.email }}{% endif %}
          </h3>
        </div>
      </div>
    </div>
  </div>
</div>

{% include 'components/footer.html' %}

web/templates/index/search-demo.html
{% load staticfiles %}
{% include 'components/header.html' %}

<div class="full-container">
    <div class="container">           
        <div class="row search-wrapper">            
            <div class="col-sm-8 col-sm-offset-2 col-xs-12">
                <div class="search-box">
                    <form action="." method="POST" class="search-form">
                        {% csrf_token %}
                        <input id="id_name" type="text" name="search_name" maxlength="127" class="form-control search-input" placeholder="find coupon here.."/>
                        <button class="btn btn-link search-btn">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </form>
                </div>
            </div>
        </div>

        <div class="content row">
            {% for ticket in tickets %}
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <a class="coup-link" href="{% url 'index:detail' ticket.id %}">
                        <div class="coupon-sell">

                            <img
                                class="coup-img"
                                src="{{ ticket.ticket_image_url }}"
                                onError="this.onerror=null;this.src='https://kfcbd.com/wp-content/uploads/2016/11/kfc-logo.png'"
                            >
                            <div class="coup-text-wrapper">
                            <div class="coup-left">
                                <p class="coup-text">name: {{ ticket.name }}</p>
                                <p class="coup-text">exp: {{ ticket.expire_date }}</p>
                            </div>
                            <div class="coup-right">
                                <p class="coup-text">{{ ticket.price }} {{ ticket.currency }}</p>
                            </div>
                            </div>
                        </div>
                    </a>
                </div>
                {% if forloop.counter|divisibleby:"3" %}
                    </div><div class="content row">
                {% endif %}
            {% endfor %}
        </div>
        </div>
    </div>
</div>

{% include 'components/footer.html' %}

web/templates/index/store-list.html
{% load staticfiles %}
{% include 'components/header.html' %}
<div class="container">
    <div class="content row">
        {% for store in stores %}
            <div class="col-md-4 col-sm-6 col-xs-12">
                    <a class="coup-link" href="{% url 'index:store' store.id %}">
                        <div class="coupon-sell">
                            <img
                                class="coup-img"
                                src="{{ store.profile_image_url }}"
                                onError="this.onerror=null;this.src='https://kfcbd.com/wp-content/uploads/2016/11/kfc-logo.png'"
                            >
                            <div class="coup-center">
                                <p class="coup-text" align="center">{{ store.store_name }}</p>
                            </div>
                        </div>
                    </a>
            </div>
            {% if forloop.counter|divisibleby:"3" %}
                </div><div class="row">
            {% endif %}
        {% endfor %}
    </div>
</div>

{% include 'components/footer.html' %}

web/templates/index/store.html
{% load staticfiles %}
{% include 'components/header.html' %}
<div class="container">
    <div class="profile-title detail-content" style="margin-top:10px;">
        <img class="profile-image" src="{{ store.profile_image_url }}" alt="profile">
    </div>
    <div class="profile-title detail-content" style="margin-top:15px;">
        <p style="font-size:160%;">Store's Name: {{store.store_name}}</p>
    </div>
    <div class="content row">
        {% for ticket in tickets %}
            <div class="col-md-4 col-sm-6 col-xs-12">
                <a class="coup-link" href="{% url 'index:detail' ticket.id %}">
                    <div class="coupon-sell">
                        <img
                            class="coup-img"
                            src="{{ ticket.ticket_image_url }}"
                            onError="this.onerror=null;this.src='https://kfcbd.com/wp-content/uploads/2016/11/kfc-logo.png'"
                        >
                        <div class="coup-text-wrapper">
                            <div class="coup-mini-logo">
                                    <img
                                        class="profile-mini-logo"
                                        src="{{ store.profile_image_url }}"                                            onError="this.onerror=null;this.src='https://kfcbd.com/wp-content/uploads/2016/11/kfc-logo.png'"
                                        >
                            </div>
                            <div class="coup-left">
                                <p class="coup-text">name: {{ ticket.name }}</p>
                                <p class="coup-text">exp: {{ ticket.expire_date }}</p>
                            </div>
                            <div class="coup-right">
                                <p class="coup-text">{{ ticket.price }} {{ ticket.currency }}</p>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            {% if forloop.counter|divisibleby:"3" %}
                </div><div class="row">
            {% endif %}
        {% endfor %}
    </div>
</div>

{% include 'components/footer.html' %}

web/templates/index/wallet.html
{% include 'components/header.html' %}

<div class="full-container">
  <div class="container">
    {% include 'components/tabbar.html' %}
    <table class="table table-bordered">
      <thead>
        <tr>
          <th class="text-center">Name</th>
          <th class="text-center">Amount</th>
          <th class="text-center">Redeem</th>
        </tr>
      </thead>
      <tbody>
        {% for wallet in wallets %}
          <tr>
            <td>{{ wallet.name }}</td>
            <td>{{ wallet.amount }}</td>
            <td><a href="{% url 'customer:motherload' %}">redeem</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% include 'components/footer.html' %}