web/go_coup/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

# LOGIN_URL = 'login'
# LOGOUT_URL = 'logout'
# LOGIN_REDIRECT_URL = 'home'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('index.urls', namespace='index')),
    url(r'^user/',include('usermanage.urls', namespace='user')),
    url(r'^store/',include('storemanage.urls', namespace='store')),
    url(r'^customer/',include('customermanage.urls', namespace='customer')),
    url(r'^shopping/',include('market.urls', namespace='market')),
    url(r'^search/', include('haystack.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),

]

web/index/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

app_name = 'index'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detail/(?P<ticket_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^catalog/$', views.catalog, name='catalog'),
    url(r'^search-demo/$', views.searchDemo, name='search-demo'),
    url(r'^get-point/(?P<store>.+)/(?P<key>.+)/$', views.getPoint, name='get-point'),
    url(r'^sw.js', views.sw, name='service-worker'),
    url(r'^brand/(?P<store_id>[0-9]+)/$', views.store, name='store'),
    url(r'^store-list/$', views.store_list, name='store_list'),
]

web/usermanage/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'user'
LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = 'home'
SOCIAL_AUTH_FACEBOOK_KEY = '504951239878757'  # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = 'd6e8030eb8a53f82a34c169139993bd4' # App Secret

urlpatterns = [
    url(r'^register/$', views.customerRegister, name='customer-register'),
    url(r'^store-register/$', views.storeRegister, name='store-register'),
    url(r'^login/$',views.singin, name='login'),
    url(r'^logout/$',views.signout, name='logout'),
    url(r'^tempprofile/$',views.profile, name='profile'),
    url(r'^profile/$',views.customerProfile, name='customer-profile'),
    url(r'^coupon/$',views.customerCoupon, name='customer-coupon'),
    url(r'^wallet/$',views.customerWallet, name='customer-wallet'),
    url(r'^customertest/$',views.customertest, name='customertest'),
    url(r'^storetest/$',views.storetest, name='storetest'),
    url(r'^setting/$',views.customerSetting, name='customer-setting'),
]

web/templates/components/footer.html
{% load staticfiles %}
  <div class="footer">
      <div class="container">
          <div class="row">
            <div class="col-sm-4 col-sm-offset-8 col-xs-12">
              <h3>Contact us</h3>
              <p>Dev: <a class="footer-link" href="https://twitter.com/monthol8th">@monthol8th</a></p>
              <p>CEO: <a class="footer-link" href="https://www.facebook.com/evee.monpriya">evee.monpriya</a></p>
            </div>
          </div>
      </div>
  </div>
  <script src="{% static 'noti.js' %}"></script>
</body>
</html>

web/templates/components/header.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://fonts.googleapis.com/css?family=Kanit:300,400,700" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/profile.css' %}">
  <link rel="stylesheet" href="{% static 'css/cart.css' %}">
  <link rel="stylesheet" href="{% static 'css/coupon.css' %}">
  <link rel="stylesheet" href="{% static 'css/login.css' %}">
  <link rel="stylesheet" href="{% static 'css/detail.css' %}">  

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <title>Go Coup</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.9.1/sweetalert2.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.9.1/sweetalert2.min.css">
  <script src="{% static 'sw-toolbox/companion.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
  <script src="{% static 'js/script.js' %}"></script>
  
  <script type="text/javascript" src="{% static 'js/qrcode.min.js' %}"></script>
  <script src="https://use.fontawesome.com/de2946df28.js"></script>  
</head>
<body>
  <nav class="navbar navbar-default header">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/" class="navbar-brand">
          <img class="logo" src="{% static 'images/logo-white.png' %}" alt="logo">
        </a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            {% if is_store %}
              <li><a href="{% url 'store:index' %}">Go to Store</a></li>
              <li><a href="{% url 'user:logout' %}">logout</a></li>
            {% else %}
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'user:customer-profile' %}">Profile</a></li>
                  <li><a href="{% url 'user:customer-wallet' %}">Wallet</a></li>
                  <li><a href="{% url 'user:customer-coupon' %}">Coupon</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="{% url 'user:customer-setting' %}">Setting</a></li>
                  <li><a href="{% url 'user:logout' %}">Logout</a></li>
                </ul>
              </li>
              <li onclick="goToCart()">
                <a href="#">
                  <img class="logo-nav" src="{% static 'images/cart.png' %}" alt="">
                </a>
              </li>
            {% endif %}
          {% else %}
            <li><a href="{% url 'user:login' %}">Login</a></li>
            <li><a href="{% url 'user:customer-register' %}">Register</a></li>
          {% endif %}
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

web/templates/components/tabbar.html
<div class="profile-nav">
  <a class="profile-nav-btn" href="{% url 'user:customer-profile' %}">
    profile
  </a>
  <a class="profile-nav-btn" href="{% url 'user:customer-wallet' %}">
    wallet
  </a>
  <div class="profile-image-wrapper">
    <img class="profile-image" src="https://www.what-dog.net/Images/faces2/scroll001.jpg" alt=" profile">
  </div>
  <a class="profile-nav-btn" href="{% url 'user:customer-coupon' %}">
    coupon
  </a>
  <a class="profile-nav-btn" href="{% url 'user:customer-setting' %}">
    setting
  </a>
</div>